[package]
name = "oryx"
version = "0.2.0"
edition = "2021"
rust-version = "1.80"

[dependencies]
anyhow = "1"
arboard = { version = "3", default-features = false, features = ["wayland-data-control"] }
cosmic-text = "0.17.0"
directories = "6"
image = "0.25"
open = "5"
pulldown-cmark = "0.13"
resvg = "0.45.1"
serde = { version = "1", features = ["derive"] }
softbuffer = "0.4"
syntect = { version = "5.3.0", default-features = false, features = ["default-fancy"] }
tiny-skia = "0.11"
toml = "0.8"
winit = "0.30"

[dev-dependencies]
image = "0.25"
