[package]
name = "oryx"
version = "0.7.1"
edition = "2021"
license = "GPL-3.0-only"
rust-version = "1.80"

[dependencies]
anyhow = "1"
arboard = { version = "3", default-features = false, features = ["wayland-data-control"] }
cosmic-text = "0.17.0"
directories = "6"
image = "0.25"
open = "5"
pulldown-cmark = "0.13"
resvg = "0.45.1"
rfd = "0.17.2"
serde = { version = "1", features = ["derive"] }
softbuffer = "0.4"
syntect = { version = "5.3.0", default-features = false, features = ["default-fancy"] }
tiny-skia = "0.11"
toml = "0.8"
ureq = { version = "3.2.1", default-features = false, features = ["native-tls", "gzip"] }
winit = "0.30"

[dev-dependencies]
image = "0.25"

[build-dependencies]
ico = "0.5.0"
resvg = "0.45.1"

[target."cfg(windows)".dependencies]
winreg = "0.56.0"
