name: ci
on: [push, pull_request]
jobs:
  check:
    runs-on: docker
    container:
      image: rust:latest
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4
      - run: rustup component add clippy rustfmt
      - run: rustup target add x86_64-pc-windows-msvc aarch64-apple-darwin
      - run: cargo fmt --check
      - run: cargo clippy --all-targets -- -D warnings
      - run: cargo build
      - run: cargo test
      - run: cargo clippy --target x86_64-pc-windows-msvc -- -D warnings
      - run: cargo clippy --target aarch64-apple-darwin -- -D warnings
